import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { EvidenceManager } from './evidence-manager';

export async function generateReport(session: any, activeFolder?: string): Promise<string> {
    return new Promise((resolve, reject) => {
        try {
            const document = new PDFDocument({ margin: 50, bufferPages: true });
            const evidenceDir = EvidenceManager.getEvidenceDir(session.sessionId, activeFolder);
            const pdfPath = path.join(evidenceDir, `Report-${session.sessionId}.pdf`);
            const stream = fs.createWriteStream(pdfPath);

            document.pipe(stream);

            // Page setup & styling helper
            const addFooter = () => {
                const bottomRange = document.page.height - 50;
                document.fontSize(10).fillColor('gray')
                    .text('Generated by Zero Code', 50, bottomRange, { align: 'left' })
                    .text(`${document.bufferedPageRange().count}`, 50, bottomRange, { align: 'right' });
            };

            // Section 1: Header
            document.fontSize(24).font('Helvetica-Bold').fillColor('#3b82f6').text('Zero Code', { align: 'right' });
            document.fontSize(14).fillColor('gray').text('Automated QA Test Report', { align: 'right' });
            document.moveDown();
            document.strokeColor('#e5e7eb').lineWidth(1).moveTo(50, document.y).lineTo(550, document.y).stroke();
            document.moveDown(2);

            document.fontSize(12).fillColor('black').font('Helvetica-Bold').text('Session Info:');
            document.font('Helvetica').fontSize(10);
            document.text(`Session ID: ${session.sessionId}`);
            document.text(`Date & Time: ${session.date}`);
            document.text(`URL Tested: ${session.url}`);
            document.moveDown();
            document.font('Helvetica-Bold').text('Test Description:');
            document.font('Helvetica').text(session.description);
            document.moveDown(2);

            // Section 1: Summary Box
            const passRate = session.totalPassed + session.totalFailed > 0
                ? Math.round((session.totalPassed / (session.totalPassed + session.totalFailed)) * 100)
                : 0;

            document.rect(50, document.y, 500, 60).fillAndStroke('#f9fafb', '#e5e7eb');
            document.fillColor('black').fontSize(10).font('Helvetica-Bold');
            document.text(`Total Steps: ${session.totalPassed + session.totalFailed}`, 60, document.y - 50);
            document.fillColor('green').text(`Passed: ${session.totalPassed}`, 160, document.y - 12);
            document.fillColor('red').text(`Failed: ${session.totalFailed}`, 260, document.y - 12);
            document.fillColor('black').text(`Pass Rate: ${passRate}%`, 360, document.y - 12);

            const messageColor = session.totalFailed === 0 && session.totalPassed > 0 ? 'green' : (session.totalFailed > 0 ? 'red' : 'black');
            const messageText = session.totalFailed === 0 && session.totalPassed > 0 ? 'ALL TESTS PASSED' : (session.totalFailed > 0 ? 'TESTS FAILED' : 'NO TESTS RUN');
            document.fillColor(messageColor).text(messageText, 450, document.y - 12);
            document.moveDown(4);

            // Section 2: Step by step Table
            document.fontSize(14).fillColor('black').font('Helvetica-Bold').text('Step by Step Results');
            document.moveDown();

            let yPos = document.y;
            document.fontSize(10).font('Helvetica-Bold');
            document.text('Step', 50, yPos);
            document.text('Type', 90, yPos);
            document.text('Description', 150, yPos);
            document.text('Status', 400, yPos);
            document.text('Notes', 450, yPos);

            yPos += 20;
            document.strokeColor('#e5e7eb').lineWidth(1).moveTo(50, yPos).lineTo(550, yPos).stroke();
            yPos += 10;

            document.font('Helvetica');
            for (const step of session.steps) {
                if (yPos > document.page.height - 100) {
                    document.addPage();
                    yPos = 50;
                }

                const bgColor = step.status === 'passed' ? '#ecfdf5' : (step.status === 'failed' ? '#fef2f2' : '#ffffff');
                document.rect(50, yPos - 5, 500, 30).fill(bgColor);

                document.fillColor('black');
                document.text(step.index.toString(), 50, yPos);
                document.text(step.type === 'action' ? 'Action' : 'Assertion', 90, yPos);

                // Truncate description if too long
                const desc = step.label.length > 40 ? step.label.substring(0, 37) + '...' : step.label;
                document.text(desc, 150, yPos);

                const statusSymbol = step.status === 'passed' ? 'PASS' : (step.status === 'failed' ? 'FAIL' : 'PEND');
                document.fillColor(step.status === 'passed' ? 'green' : (step.status === 'failed' ? 'red' : 'gray')).text(statusSymbol, 400, yPos);

                document.fillColor('black');
                let notes = '';
                if (step.status === 'failed' && step.error) {
                    notes = step.error.substring(0, 20) + '...';
                }
                document.text(notes, 450, yPos);

                yPos += 30;

                // If failed and screenshot exists, embed it
                if (step.status === 'failed' && step.screenshotPath && fs.existsSync(step.screenshotPath)) {
                    if (yPos > document.page.height - 300) {
                        document.addPage();
                        yPos = 50;
                    }
                    try {
                        document.image(step.screenshotPath, 50, yPos, { width: 500 });
                        yPos += 300; // rough estimate of image height
                    } catch (e) {
                        document.text(`(Screenshot failed to load: ${step.screenshotPath})`, 50, yPos);
                        yPos += 20;
                    }
                }
            }

            document.addPage();

            // Section 3: Appendix
            document.fontSize(14).fillColor('black').font('Helvetica-Bold').text('Appendix: Generated Test Script');
            document.moveDown();

            document.fontSize(8).font('Courier').fillColor('#374151');
            document.text(session.code, {
                width: 500,
                align: 'left'
            });

            // Add footers across all pages
            const pages = document.bufferedPageRange();
            for (let i = 0; i < pages.count; i++) {
                document.switchToPage(i);
                addFooter();
            }

            document.end();
            stream.on('finish', () => resolve(pdfPath));
            stream.on('error', (e) => reject(e));
        } catch (error) {
            reject(error);
        }
    });
}